### ISSUE TITLE
New ips to block?

### ISSUE THREAD

**Issue by Sjoerd001** [Xorlent/Stretchoid#2] opened 2024-07-21 15:39 UTC
<pre>104.40.75.145
Checking IP: <b><u>145.75.40.104.in-addr.arpa domain name pointer azpdws94.stretchoid.com.
</u></b>AS info: <b><u>US - AS8075 - MICROSOFT-CORP-MSN-AS-BLOCK 104.40.0.0/13 range ( 104.40.0.0 - 104.47.255.255)</u></b>

<br><b><font color="red"><i><hr><font color="green">(1) 104.40.75.145 not in whitelist database</font><font color="red"><br><font color="green">(2) 104.40.75.145 not in whitelist database</font><font color="red"><br><font color="green">(3) 104.40.75.145 not in whitelist database</font><font color="red"><br><hr></font><br><br><br>IP is part of: AS8075 104.40.0.0/13<br><br>AS3549 -&gt; AS3356<br><br><br>==&gt; <font color="blue"><i></i></font><i> &lt;==</i></font></font></i></font></b><i><font color="red"><br><br></font>
listed by dnsbl-1.uceprotect.net: IP 104.40.75.145 is UCEPROTECT-Level 1 listed. See http://www.uceprotect.net/rblcheck.php?ipr=104.40.75.145listed by dnsbl-2.uceprotect.net: Net 104.40.0.0/13 is UCEPROTECT-Level2 listed because 408 impacts are seen from MICROSOFT-CORP-MSN-AS-BLOCK, US/AS8075 there. See: http://www.uceprotect.net/rblcheck.php?ipr=104.40.75.145listed by cbl.abuseat.org: Error: open resolver; https://check.spamhaus.org/returnc/pub/172.71.97.238/
--

</i></pre>

**Comment by Xorlent** [comment] 2024-07-21 16:07
Thank you for this.  Yes, the process of adding all of the IPs takes a considerable amount of time due to the fact that the Stretched IPs are unlisted.  We have not yet completed one full scan; I estimate it will be a few months before the dataset is complete.  Every few days this list will become more complete as we discover more entries.  If I can figure out a way to ensure complete coverage more quickly, I will do it.  Perhaps I will process the UCEProtect list to at least capture the ones listed there this week.

**Comment by Xorlent** [comment] 2024-07-29 15:26
I expect this reported IP range will be included in the list this Wednesday.

**Comment by Xorlent** [comment] 2024-07-29 20:30
Confirmed, your reported IP address was picked up and is now in the list.  Thanks again.

**Closed by Xorlent** 2024-07-29 20:30 UTC
